version: '3.8'

services:
  db:
    image: postgres:14
    container_name: cyclos-db
    environment:
      POSTGRES_DB: cyclos
      POSTGRES_USER: cyclos
      POSTGRES_PASSWORD: cyclospass
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - cyclos-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  cyclos:
    image: cyclos/cyclos:latest
    container_name: cyclos-app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: cyclos
      DB_USER: cyclos
      DB_PASSWORD: cyclospass
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - cyclos-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  cyclos-net:

volumes:
  db_data:
